name: NotzScoreboard
version: '3.3'
main: dev.kaato.notzscoreboard.NotzScoreboard
softdepend: [ PlaceholderAPI, NotzAPI ]

commands:
  nscoreboard:
    description: notzscoreboard admin command
    usage: /nsb
    aliases:
      - notzscoreboard
      - notzsb
      - nsb
permissions:
  notzscoreboard.admin:
    description: Admin perm
    default: false