name: NotzScoreboard
version: 3.2
main: dev.kaato.notzscoreboard.Main
softdepend: [PlaceholderAPI]

commands:
  nscoreboard:
    description: notzscoreboard admin command
    usage: /nsb
    aliases:
      - notzscoreboard
      - notzsb
      - nsb
permissions:
  notzscoreboard.admin:
    description: Admin perm
    default: false